export enum EffectType {
    BLINK = "BLINK",
    PULSE = "PULSE",
    FADETOBLACK = "FADETOBLACK",
    FADEUP = "FADEUP",
    ROTATECLOCKWISE = "ROTATECLOCKWISE",
    ROTATEANTICLOCKWISE = "ROTATEANTICLOCKWISE",
    SCROLLLEFT = "SCROLLLEFT",
    SCROLLRIGHT = "SCROLLRIGHT",
    SCROLLUP = "SCROLLUP",
    SCROLLDOWN = "SCROLLDOWN"
}