export enum EffectType {
    BLINK = "BLINK",
    PULSE = "PULSE",
    FADETOBLACK = "FADETOBLACK",
    FADEUP = "FADEUP",
    ROTATECLOCKWISE = "ROTATECLOCKWISE",
    ROTATEANTICLOCKWISE = "ROTATEANTICLOCKWISE"
}