# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, implementation ]
  pull_request:
    branches: [ main, implementation ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
    # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      # Runs a single command using the runners shell
      - uses: actions/setup-node@v1
      #- run: ls -la ./rpi-led-matrix # Debugging
      - run: npm i -g rimraf typescript
      - run: npm install --prefix=./rpi-led-matrix --also=dev # also install devDependencies
      #- run: ls -la ./rpi-led-matrix/node_modules # Debugging
      #- run: ls -la ./node_modules
      - run: npm run build --prefix=./rpi-led-matrix
      - run: npm install
      #- run: ls -la ./node_modules # Debugging
      - run: npm run build
